# Generated by Django 2.1.dev20180412031711 on 2018-04-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
    ]
